app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Authentication routes...
Route::get('/', 'Auth\AuthController@getLogin');
Route::get('admin/login', 'Auth\AuthController@getLogin');
Route::post('admin/login', 'Auth\AuthController@postLogin');
Route::get('admin/logout', 'Auth\AuthController@getLogout');


// secure admin pages in group.
Route::group(['middleware' => 'auth'],
function()
{
    Route::get('admin/dash', 'DashController@index');
    Route::resource('admin/courses', 'CoursesController');
    Route::resource('admin/modules', 'ModulesController');
    Route::resource('admin/items', 'ItemsController');
    Route::resource('admin/itemmodule', 'ItemModuleController');
}
);

app/Http/Controllers/CoursesController.php
<?php

namespace App\Http\Controllers;
use App\User;
use DB;
use App\Course;
use Illuminate\Http\Request;
use Redirect;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use Auth;

class CoursesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
    */
    public function index(Requests\CreateCoursesRequest $request)
    {
        // return a list of all courses
        $allCourses = Course::all();
        return view('admin.courses.list', ['allCourses' => $allCourses]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create(Requests\CreateCoursesRequest $request)
    {
        $users = User::where('admin', 0)
            ->orderBy('name', 'desc')
            ->get();

        $moduleCourseAssociations = Course::moduleCourseAssociations(0);

        return view('admin.courses.create', ['users' => $users])->with(['moduleCourseAssociations' => $moduleCourseAssociations]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Requests\CreateCoursesRequest  $request
     * @return Response
     */
    public function store(Requests\CreateCoursesRequest $request)
    {
        $course = new Course;

        $course->title = $request->title;
        $course->code   = $request->code;
        $course->leader = $request->courseleader;

        $course->save();

        $courseModules = $request->get('courseModules');

        // write module associations
        if (count($courseModules) > 0 ) {
            foreach ($courseModules as $module_id) {
                DB::table('course_module')->insert([
                    'course_id' => $course->id, 'module_id' => $module_id
                ]);
            }
        }

        return Redirect::route('admin.courses.show', [$course]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show(Requests\CreateCoursesRequest $request, $id)
    {
        $course = Course::findORFail($id);
        $courseleader = User::find($course->leader);
        return view('admin.courses.show', ['course' => $course])->with(['courseleader' => $courseleader]);


    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit(Requests\CreateCoursesRequest $request, $id)
    {
        $users = User::where('admin', 0)
            ->orderBy('name', 'desc')
            ->get();
        $userselector = array();
        foreach($users as $user) {
            $userselector[$user->id] = $user->name;
        };
        $course = Course::findOrFail($id);
        // call the coursemoduleassociations method from the courses model than chain this to the return to the view.
        $moduleCourseAssociations = Course::moduleCourseAssociations($id);

        // pass over two arrays/variables to the view.
        return view('admin.courses.edit', ['course' => $course])->with(['userselector' => $userselector])->with(['moduleCourseAssociations' => $moduleCourseAssociations]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return Response
     */

    public function update(Requests\CreateCoursesRequest $request, $id)
    {
        $course = Course::findORFail($id);

        $course->update([


            'title' => $request->get('title'),
            'code' => $request->get('code'),
            'leader' => $request->get('courseleader')
        ]);

        $moduleCourseAssociations = Course::moduleCourseAssociations($id);
        $courseModules = $request->get('courseModules');
        foreach ($moduleCourseAssociations as $module)
        {
            $skipped = false;
            // error capture for having no modules associated
            if (count($courseModules) > 0 ) {
                // check if association already exists if it does remove it from the $courseModules array then remove it frm the db
                if ($module->checked == 1 && (($key = array_search($module->id, $courseModules)) !== false)) {
                    unset($courseModules[$key]);
                    $skipped = true;
                }
            }
            // delete any removed associations
            if($module->checked == 1 && !$skipped)
            {
                DB::table('course_module')->where('course_id', '=', $course->id)->where('module_id', '=', $module->id)->delete();
            }
            unset($key);
        }
        // write new associations
        if (count($courseModules) > 0 ) {
            foreach ($courseModules as $module_id) {
                DB::table('course_module')->insert([
                    'course_id' => $course->id, 'module_id' => $module_id
                ]);
            }
        }

        return Redirect::route('admin.courses.show', $course->id)->with('message', 'Your course has been updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy(Requests\CreateCoursesRequest $request, $id)
    {
        // delete
        Course::destroy($id);

        // redirect
        //Session::flash('message', 'Successfully deleted the Course!');
        return \Redirect::route('admin.courses.index');

    }
}

resources/views/admin/courses/courseModuleAssociations.blade.php
@foreach($moduleCourseAssociations as $module)
    <div class="left large-2 medium-2 small-6 columns">
        {!! Form::checkbox('courseModules['.$module->id.']', $module->id, $module->checked ) !!}
        {!! Form::label('courseModules['.$module->id.']', $module->title) !!}
    </div>
@endforeach

resources/views/admin/courses/create.blade.php
@extends('layouts.master')

@section('title', 'Add a New Course')
@stop

@section('content')

    <h1 class="small-12 columns">Add new Course</h1>

        @if (count($errors) > 0)
            <div class="alert-box alert large-12 columns">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

    <form method="POST" action="{{ url('admin/courses') }}" enctype="multipart/form-data" id="form" data-abide>
        <!-- Title Form Input-->
        <div class="large-12 columns">
            <label for="Title">Title:</label>
            <input type="text" id="title" name="title" placeholder="Course Title" value="{{ Input::old('title') }}" required >
            <small class="error">A title is required.</small>
        </div>
        <!-- code Form Input-->
        <div class="large-12 columns">
            <label for="code">Course Code:</label>
            <input type="text" id="code" name="code" placeholder="Course Code" value="{{ Input::old('code') }}" required >
            <small class="error">A course code is required. example BIS123456789</small>
        </div>
        <!-- Leader Form Dropdown-->
        <div class="large-12 columns">
            <label for="courseleader">Leader:</label>
            <select id="cousrseleader" name="courseleader">
                @foreach($users as $user)
                    <option value="{{ $user->id }}">{{ $user->name }}</option>
                @endforeach
            </select>
        </div>
        <!-- add module associtation checkboxes partial blade -->
        <div class="row large-12 columns ">
            <h2>Module Associations</h2>
            @if ( count($moduleCourseAssociations) > 0)
                @include('admin.courses.courseModuleAssociations')
            @endif
        </div>
        <!-- Course submit button -->
        <div class="large-12 columns">
            <button id="submit" name="submit" class="button right">Create Course</button>
        </div>
        {!! csrf_field() !!}
    </form>

@stop

resources/views/admin/courses/edit.blade.php
@extends('layouts.master')

@section('title')
    Edit - {{ $course->title }}
@stop

@section('content')

    <h1 class="small-12 columns">Edit - {{ $course->title }}</h1>

    @if (count($errors) > 0)
        <div class="alert-box alert large-12 columns">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    {!! Form::model($course, array('method' => 'put', 'route' => ['admin.courses.update', $course->id], 'data-abide' => '')) !!}
        <!-- Title Form Input-->
        <div class="large-12 columns">
            {!! Form::label('title:', 'Course title:') !!}
            {!! Form::text('title', Input::old('title'), array('placeholder'=>'Course Title', 'required' => '')) !!}
        </div>

        <!-- code Form Input-->
        <div class="large-12 columns">
            {!! Form::label('code', 'Course code:') !!}
            {!! Form::text('code', Input::old('code'), array('placeholder'=>'Course Code', 'required' => '')) !!}
        </div>
        <!-- Leader Form Dropdown-->
        <div class="large-12 columns">
            {!! Form::label('courseleader', 'Leader:') !!}
            <!-- moved the logic to the controller -->
            {!! Form::select('courseleader', $userselector, $course->leader) !!}
        </div>
        <!-- add module associtation checkboxes partial blade -->
        <div class="row large-12 columns ">
            <h2>Module Associations</h2>
                @if ( count($moduleCourseAssociations) > 0)
                    @include('admin.courses.courseModuleAssociations')
                @endif
        </div>
        <!-- Course submit button -->
        <div class="large-12 columns">
            {!! Form::submit('Update Course', array('class'=>'button right')) !!}
        </div>
        {!! csrf_field() !!}
    {!! Form::close() !!}
@stop

resources/views/admin/courses/list.blade.php
@extends('layouts.master')
@section('title')
    All Courses
@stop
@section('content')
    <?php $adminstatus = (Auth::user()->admin) ?>


    <h1 class="small-12 columns">Courses @if ($adminstatus == '1') <a href="{{ url('admin/courses/create') }}" class="button small success right">
            Add a new course
        </a> @endif</h1>

    @if(Auth::check())
        <!--  The user is logged in... -->
    <div class="row small-12 columns">

        @if ($adminstatus == '1')

            <!-- return a list of all courses -->
            <div class="small-12 columns">
                @foreach($allCourses as $aCourse)
                    <div class="row">
                        {!! Form::open(array('url' => '/admin/courses/' . $aCourse->id)) !!}
                        <a href="{{ route('admin.courses.show', [$aCourse->id]) }}" class="item">{{ $aCourse->title }}</a>
                        {!! Form::hidden('_method', 'DELETE') !!}
                        {!! Form::submit('Delete this Course', array('class' => 'button tiny alert right', 'id' => $aCourse->title . ' delete', 'name' => $aCourse->title . ' delete')) !!}
                        {!! Form::close() !!}
                        <hr />

                    </div>

                @endforeach
                </div>

        @else

        <!-- return only courses the staff are course leaders of and if none then return a message saying none to show. -->
            <?php $myCourses = $allCourses->where('leader', (Auth::user()->id)) ?>
            <div class="small-12 columns">
                @foreach ($myCourses as $myCourse)
                    <div class="row">
                        <a href="{{ route('admin.courses.show', [$myCourse->id]) }}" class="item">{{ $myCourse->title }}</a>
                    </div>
                @endforeach
            </div>

        @endif
    </div>

    @endif



@stop

resources/views/admin/courses/show.blade.php
@extends('layouts.master')
@section('title')
    Course - {{ $course->code }} - {{ $course->title }}
@stop
@section('content')

    @if ( Session::get('message'))
        <div class="alert-box warning large-12 columns">
            {{ Session::get('message') }}
        </div>
    @endif
    <h1 class="small-12 columns">{{ $course->title }}</h1>
    <div class="row small-12 columns">
        <p><strong>Course Code:</strong> {{ $course->code }}</p>
        <p><strong>Course Leader:</strong> {{ $courseleader->name }}</p>
        <div>
            <h2>Associated Modules</h2>
            @if ( !$course->modules->count() )
                Your course has no Modules linked.
            @else
                <ul class="no-bullet small-12 columns">
                    @foreach( $course->modules as $module )
                        <li><a href="{{ route('admin.modules.show', [$module->id]) }}">{{ $module->title }} - {{ $module->code }}</a></li>
                    @endforeach
                </ul>
            @endif
        </div>
        <a href="{{ route('admin.courses.edit', $course->id) }}" class="button small warning right">Edit Course</a>

    </div>

@stop